import type { StoreCustomizationConfig, VisualPreset } from '@/schemas/customization';

type PresetProposal = Pick<StoreCustomizationConfig, 'palette' | 'typography' | 'theme'> & {
  productPresentation: StoreCustomizationConfig['layout']['productPresentation'];
};

export const CUSTOMIZATION_PRESETS: Record<VisualPreset, PresetProposal> = {
  CLASSIC: {
    palette: {
      primary: '#D9480F',
      secondary: '#241C15',
      accent: '#F59E0B',
      background: '#FFFDF9',
      surface: '#FFFFFF',
      text: '#241C15',
      mutedText: '#6B625A',
      border: '#DED7CE',
      buttonBackground: '#C2410C',
      buttonText: '#FFFFFF',
    },
    typography: {
      headingFontKey: 'bricolage',
      bodyFontKey: 'inter',
      baseSize: 'medium',
      headingWeight: 'bold',
      buttonStyle: 'solid',
      borderRadius: 'medium',
    },
    theme: { layoutTemplate: 'CLASSIC_LIST', visualPreset: 'CLASSIC' },
    productPresentation: 'LIST',
  },
  MODERN: {
    palette: {
      primary: '#1D4ED8',
      secondary: '#111827',
      accent: '#06B6D4',
      background: '#F8FAFC',
      surface: '#FFFFFF',
      text: '#111827',
      mutedText: '#475569',
      border: '#CBD5E1',
      buttonBackground: '#1D4ED8',
      buttonText: '#FFFFFF',
    },
    typography: {
      headingFontKey: 'inter',
      bodyFontKey: 'inter',
      baseSize: 'medium',
      headingWeight: 'extrabold',
      buttonStyle: 'solid',
      borderRadius: 'large',
    },
    theme: { layoutTemplate: 'MODERN_GRID', visualPreset: 'MODERN' },
    productPresentation: 'GRID',
  },
  MINIMALIST: {
    palette: {
      primary: '#111827',
      secondary: '#374151',
      accent: '#6B7280',
      background: '#FFFFFF',
      surface: '#F9FAFB',
      text: '#111827',
      mutedText: '#4B5563',
      border: '#D1D5DB',
      buttonBackground: '#111827',
      buttonText: '#FFFFFF',
    },
    typography: {
      headingFontKey: 'inter',
      bodyFontKey: 'inter',
      baseSize: 'medium',
      headingWeight: 'semibold',
      buttonStyle: 'outline',
      borderRadius: 'small',
    },
    theme: { layoutTemplate: 'CLASSIC_LIST', visualPreset: 'MINIMALIST' },
    productPresentation: 'LIST',
  },
  BURGER: {
    palette: {
      primary: '#B45309',
      secondary: '#292524',
      accent: '#FBBF24',
      background: '#FFFBEB',
      surface: '#FFFFFF',
      text: '#292524',
      mutedText: '#57534E',
      border: '#D6D3D1',
      buttonBackground: '#92400E',
      buttonText: '#FFFFFF',
    },
    typography: {
      headingFontKey: 'bricolage',
      bodyFontKey: 'inter',
      baseSize: 'large',
      headingWeight: 'extrabold',
      buttonStyle: 'solid',
      borderRadius: 'large',
    },
    theme: { layoutTemplate: 'MODERN_GRID', visualPreset: 'BURGER' },
    productPresentation: 'GRID',
  },
  PIZZA: {
    palette: {
      primary: '#B91C1C',
      secondary: '#3F1D16',
      accent: '#D97706',
      background: '#FFF7ED',
      surface: '#FFFFFF',
      text: '#3F1D16',
      mutedText: '#6B4F45',
      border: '#E7D5C8',
      buttonBackground: '#B91C1C',
      buttonText: '#FFFFFF',
    },
    typography: {
      headingFontKey: 'bricolage',
      bodyFontKey: 'inter',
      baseSize: 'medium',
      headingWeight: 'bold',
      buttonStyle: 'solid',
      borderRadius: 'medium',
    },
    theme: { layoutTemplate: 'CLASSIC_LIST', visualPreset: 'PIZZA' },
    productPresentation: 'LIST',
  },
  ACAI_DESSERT: {
    palette: {
      primary: '#6B21A8',
      secondary: '#3B0764',
      accent: '#DB2777',
      background: '#FDF4FF',
      surface: '#FFFFFF',
      text: '#2E1065',
      mutedText: '#6B4D7A',
      border: '#E9D5FF',
      buttonBackground: '#6B21A8',
      buttonText: '#FFFFFF',
    },
    typography: {
      headingFontKey: 'bricolage',
      bodyFontKey: 'inter',
      baseSize: 'medium',
      headingWeight: 'bold',
      buttonStyle: 'solid',
      borderRadius: 'pill',
    },
    theme: { layoutTemplate: 'MODERN_GRID', visualPreset: 'ACAI_DESSERT' },
    productPresentation: 'GRID',
  },
  EXECUTIVE_RESTAURANT: {
    palette: {
      primary: '#166534',
      secondary: '#172E26',
      accent: '#A16207',
      background: '#F8FAF7',
      surface: '#FFFFFF',
      text: '#172E26',
      mutedText: '#50645C',
      border: '#CDD8D2',
      buttonBackground: '#166534',
      buttonText: '#FFFFFF',
    },
    typography: {
      headingFontKey: 'bricolage',
      bodyFontKey: 'inter',
      baseSize: 'medium',
      headingWeight: 'semibold',
      buttonStyle: 'solid',
      borderRadius: 'small',
    },
    theme: { layoutTemplate: 'EDITORIAL_HERO', visualPreset: 'EXECUTIVE_RESTAURANT' },
    productPresentation: 'LIST',
  },
  DARK_PREMIUM: {
    palette: {
      primary: '#FBBF24',
      secondary: '#F59E0B',
      accent: '#FDE68A',
      background: '#171717',
      surface: '#262626',
      text: '#FAFAFA',
      mutedText: '#D4D4D4',
      border: '#525252',
      buttonBackground: '#FBBF24',
      buttonText: '#241C15',
    },
    typography: {
      headingFontKey: 'bricolage',
      bodyFontKey: 'inter',
      baseSize: 'medium',
      headingWeight: 'bold',
      buttonStyle: 'solid',
      borderRadius: 'medium',
    },
    theme: { layoutTemplate: 'EDITORIAL_HERO', visualPreset: 'DARK_PREMIUM' },
    productPresentation: 'GRID',
  },
};

export function applyVisualPreset(
  current: StoreCustomizationConfig,
  presetKey: VisualPreset,
  replacePalette: boolean,
): StoreCustomizationConfig {
  const proposal = CUSTOMIZATION_PRESETS[presetKey];
  return {
    ...structuredClone(current),
    palette: replacePalette ? structuredClone(proposal.palette) : structuredClone(current.palette),
    typography: structuredClone(proposal.typography),
    theme: structuredClone(proposal.theme),
    layout: {
      ...structuredClone(current.layout),
      productPresentation: proposal.productPresentation,
    },
  };
}
