export const RECENT_PURCHASE_WINDOW_DAYS = 180;
export const RECENT_PURCHASE_ORDER_LIMIT = 20;

export const RECENT_PURCHASE_ELIGIBLE_ORDER_STATUSES = [
  'CONFIRMED',
  'PREPARING',
  'READY',
  'OUT_FOR_DELIVERY',
  'DELIVERED',
] as const;

export const RECENT_PURCHASE_EXCLUDED_PAYMENT_STATUSES = [
  'FAILED',
  'CANCELLED',
  'REFUNDED',
] as const;
